### ISSUE TITLE
Update to recent Opal

### ISSUE THREAD

**Issue by mistergibson** [easydatawarehousing/opal-ferro#1]
First off --> Great job on Ferro, I'm very excited to experiment with it.

Are you going to update your code to ensure it is a good fit for the most recent Opal.rb? I see it is still at version 10.2.

**Comment by easydatawarehousing** [comment]
Thanks.
I will upgrade to opal 0.11 within the next couple of weeks when i've got some more time available to work on and with ferro myself. Don't expect any problems with this upgrade.
I'm curious, how did you find this library?

**Comment by mistergibson** [comment]
I was kicking around the opal.rb page and was in desperate need of a lightweight, yet capable, front-end solution. I intend upon building an end-to-end solution using Ferro and Padrino. I saw HyperLoop, and it looks extensive, but frankly Rails gives me gall stones and I avoid it like the plague. I love Padrino because it does everything Rails can do with 1/10th the bloat factor. I'm looking into Ferro in the hopes to build a universal GUI toolkit (at some point complete with WebGL / AudioPlayer / Chart supports. Ferro looks so nice and lightweight that I was smitten.

**Comment by easydatawarehousing** [comment]
Done, just released 0.11.0 version of the gem. See the changelog for the (minor) changes and fixes.

Opal.rb site is indeed a good place to start exploring front end ruby. I don't have any experience with hyperloop nor padrino. Padrino sounds very nice tho.
In my daytime job I work with rails all the time. Only when creating big, full featured, production ready applications you start appreciating all that bloat ;)
