### ISSUE TITLE
XHR: appears that Ajax Request Headers not set properly.

### ISSUE THREAD

**Issue by mistergibson** [easydatawarehousing/opal-ferro#2]
I am calling (request).xhr? on a Rack::Request object server side. It looks for header HTTP_X_REQUESTED_WITH == "XMLHttpRequest" --> this is not in your code and does not appear to get set.

My server is therefore *unable* to detect an Ajax call of any type. Is there something I've missed?

I get the url path fine that gets pushed through perfectly - just no XHR marking headers.

Thanks.

**Comment by mistergibson** [comment]
Doing a little research it is evident that JS does NOT set those header values for you, so you have to set them prior to sending. If you set:

xhr.setRequestHeader("X-Requested-With","XMLHttpRequest");

it detects the request as XHR.

So: in file ferro_xhr.js.rb if you insert (say at line 79):
`#{@xhr}.setRequestHeader('X-Requested-With', 'XMLHttpRequest')`
That should do it.

**Comment by easydatawarehousing** [comment]
Added the line you suggested, thanks.
The entire Xhr class could do with a rewrite. Current version is based on turbolinks ajax code. Taking a good look at how jquery handles ajax might be better. So I have not released a new gem yet. But if you use this gem from master this change is included.

**Comment by mistergibson** [comment]
Excellent thanks
