### ISSUE TITLE
(component).update_state not setting class -- appears to be ignored.

### ISSUE THREAD

**Issue by mistergibson** [easydatawarehousing/opal-ferro#4]
I cannot seem to reliably get .update_state to set the class flags.

I setup a default state of :hidden at object creation as child of the Document object.
when I update_state(:hidden, true) it returns an empty hash and does nothing.

Just thought I'd mention this to you.

**Comment by easydatawarehousing** [comment]
Did you add the state when creating the object? Something like this:

    class MyObject < Ferro::Element::Block
      def after_create
        add_state :hidden
      end
    end

_If_ you are using the style compositor the state should be defined as:

    'MyObject::hidden' => %w{my-display-none-css-class}

**Comment by mistergibson** [comment]
OK thanks
