### ISSUE TITLE
Question on forget_children and re-rending the component

### ISSUE THREAD

**Issue by mistergibson** [easydatawarehousing/opal-ferro#5]
I have an idea to swap out div content with other content - all are proper components.

I see how to get the parent to forget the children, but I don't see how to re-render to the dom to enforce the change. Could you provide some insights into how I could do this?
So:
1.  MyDiv.forget_children()
2.  MyDiv.add_child(:other_thingy, My::Class, {})
.... ? nothing changes on the page.

Thanks in advance.

**Comment by mistergibson** [comment]
Just as a follow up : I am using @the_parent.each_child {|c| c.destroy } to clear out child elements and components alike, but it not only zaps the children, but the @the_parent as well. ==> should I file a bug report, or am I misusing it?

**Comment by easydatawarehousing** [comment]
`@the_parent.each_child {|c| c.destroy }` ought to work and remove children both from the MOM and the DOM. You can call add_child at any time to create new elements. See [here line 85](https://github.com/easydatawarehousing/ferro-example-todolist/blob/master/app/assets/javascripts/application/components/todo.js.rb) for an example.

If you are swapping out content a lot it may be easier to add an element between the parent and the children and remove/recreate that element.

**Comment by mistergibson** [comment]
ok - thanks
